server:
  port: 8001
spring:
  application:
    name: user-sevice
  h2:
    console:
      path: '/h2-console'
      enabled: true
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE