server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: Master
          uri: https://github.com/JulioPuma/luigicode
          search-paths: config-data
  application:
    name: config-service